# Generated by Django 6.0.7 on 2026-07-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_record_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlesubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articletag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centralpointcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centralpointsubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centralpointtag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisioncategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionsubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisiontag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalsubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goaltag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalsubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaltag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notetag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategycategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategysubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategytag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlesubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='centralpoint',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='centralpointcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='centralpointsubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='centralpointtag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='decisioncategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='decisionsubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='decisiontag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='goalsubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='goaltag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='journaltag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='notecategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='notesubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategycategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategysubcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategytag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_article_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_articlecategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='articlesubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_articlesubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_articletag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='centralpoint',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_centralpoint_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='centralpointcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_centralpointcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='centralpointsubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_centralpointsubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='centralpointtag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_centralpointtag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_decision_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='decisioncategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_decisioncategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='decisionsubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_decisionsubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='decisiontag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_decisiontag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_goal_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='goalcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_goalcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='goalsubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_goalsubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='goaltag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_goaltag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_journal_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='journalcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_journalcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='journalsubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_journalsubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='journaltag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_journaltag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_note_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='notecategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_notecategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='notesubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_notesubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='notetag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_notetag_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_strategy_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='strategycategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_strategycategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='strategysubcategory',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_strategysubcategory_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='strategytag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_strategytag_user_slug'),
        ),
    ]
