# Generated by Django 6.0.7 on 2026-07-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals_by_category', to='core.journalcategory'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='journals_by_tag', to='core.articletag'),
        ),
        migrations.CreateModel(
            name='JournalSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.journalcategory')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals_by_subcategory', to='core.journalsubcategory'),
        ),
    ]
