# Generated by Django 6.0.7 on 2026-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_journal_category_journal_tags_journalsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='journals_by_tag', to='core.journaltag'),
        ),
    ]
