# Generated by Django 6.0.7 on 2026-07-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_journal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpoint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centralpoints_by_category', to='core.centralpointcategory'),
        ),
        migrations.AddField(
            model_name='centralpoint',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='centralpoints_by_tag', to='core.centralpointtag'),
        ),
        migrations.AddField(
            model_name='decision',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions_by_category', to='core.decisioncategory'),
        ),
        migrations.AddField(
            model_name='decision',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='decisions_by_tag', to='core.decisiontag'),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals_by_category', to='core.goalcategory'),
        ),
        migrations.AddField(
            model_name='goal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goals_by_tag', to='core.decisiontag'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_by_category', to='core.notecategory'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes_by_tag', to='core.notetag'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies_by_category', to='core.strategycategory'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='strategies_by_tag', to='core.strategytag'),
        ),
        migrations.CreateModel(
            name='CentralPointSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.centralpointcategory')),
            ],
        ),
        migrations.AddField(
            model_name='centralpoint',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centralpoints_by_subcategory', to='core.centralpointsubcategory'),
        ),
        migrations.CreateModel(
            name='DecisionSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.decisioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions_by_subcategory', to='core.decisionsubcategory'),
        ),
        migrations.CreateModel(
            name='GoalSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.goalcategory')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals_by_subcategory', to='core.goalsubcategory'),
        ),
        migrations.CreateModel(
            name='NoteSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.notecategory')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_by_subcategory', to='core.notesubcategory'),
        ),
        migrations.CreateModel(
            name='StrategySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.strategycategory')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies_by_subcategory', to='core.strategysubcategory'),
        ),
    ]
