# Generated by Django 6.0.7 on 2026-07-12 10:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_centralpoint_category_centralpoint_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='best_case',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What is the best case scenario?'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='bothering',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What is bothering me? Gather all the data you can on the situation.'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='likely_scenario',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What is the likely to happen scenario?'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='possible_solutions',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What are the possible solutions?'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='recommended_solution',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Which is the recommended solution?'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='root_cause',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What might be the root cause of the problem?'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='worst_case',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What is the worst case scenario?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='before_success',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Have others done it successfully before, if yes what strategies have they used to do so?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='cost_not_action',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What will be the cost if I dont change or take action?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='have_resources_missing',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Do I have the resources and capabilities to achieve the goal? If not what I am missing?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='how_much_many',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How much/many?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='involved_who',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Who is involved in this goal?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='outcome',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What do I want to accomplish?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pains_linked',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Which pain or pains have a linked?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pleasures_action',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What pleasures I will gain by following through?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pleasures_not_action',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What pleasure or pleasures have I gained by not taking action?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_indicator',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How do I know if I have reached my goal?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='purpose',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Why do I want to achieve this goal?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='relevance',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Is this goal relevant to your other goals, how it can relate?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time_resources_reachable',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Is this goal reachable given the time and resources?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='when_conditions',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='When do I want to achieve this goal? Specify conditions.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='where',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Where is this goal to be achieved?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='why_is_realistic',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Is this goal realistic and within reach?'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='Weeknesses',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Weaknesses'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='finalized_strategy',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='What is your finalized Strategy?'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='opportunities',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Opportunities'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='opportunities_advantages',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How to take advantage of your opportunities?'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strenght',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Strenghts'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strenghts_advantages',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How to take advantage of your strenghts'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='threats',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Threats'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='threats_prevention',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How to prevent threats from happening?'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='weekness_minimization',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='How to take improve or minimize your weaknesses?'),
        ),
    ]
