# Generated by Django 6.0.7 on 2026-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_decision_best_case_alter_decision_bothering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goals_by_tag', to='core.goaltag'),
        ),
    ]
